### ISSUE TITLE
Maybe a small mistake in UELoss

### ISSUE THREAD

**Issue by JeppeThagaardVP** [super-AND/super-AND#1]
hi, 

I maybe found a small mistake in the current code when calculating the UELoss:
![image](https://user-images.githubusercontent.com/38493325/66996301-caee7600-f0d0-11e9-8434-204d8b0a5fd8.png)

You are calculating loss_e two times, with the outputs not set to -10. I.e. not using outputs_e. In the paper, you write:
"represents the similarity between instances **except for instance itsel**f (Eq 11)"

Can you please verify?

**Comment by super-AND** [comment]
Thank you for pointing out typos in our repository. We made a mistake when we cleaned up our code. Upper line "loss_e = criterion2(outputs_e) / inputs.size(0)" is correct. We'll correct the code.
